### ISSUE TITLE
Simple way to add a streamer

### ISSUE THREAD

**Issue by Wikunia** [Julia-Streamers/StreamerSite#11]
I'm thinking about creating a command like:
```
\streamer
```
which takes 4 inputs maybe:

```
\streamer{twitch_name}{Name}{path_to_streamer_logo}{description}
```

this then creates something like: 

https://www.w3schools.com/howto/howto_css_cards.asp

(I have to sense for styling :smile: )

with a twitch badge as described in #6 

Thoughts @TheCedarPrince ?

**Comment by Wikunia** [comment]
So in the `config.md` we would have something like:
```
\newcommand{\streamer}[4]{@@card @@avatar #3 @@ @@content @@badge shields stuff with #1 @@ @@name #2 @@ # 4@@ @@}
```

I probably messed something up but you hopefully get the idea. `@@card` will i.e. create `<div class="card">`

**Comment by TheCedarPrince** [comment]
I really like the idea! Not entirely sure how to implement it. Would you be willing to start a PR on the idea? @Wikunia?

We could just go with the shields from #6 for now.
