### ISSUE TITLE
Determine Best Way to Ping Twitch API

### ISSUE THREAD

**Issue by TheCedarPrince** [Julia-Streamers/StreamerSite#2]
## Problem

One of the biggest features of the website will be determining what streamer is active when. Therefore, we need a simple yet elegant method to:

1. Ping the Twitch API to determine who is streaming on Julia programming.
2. Update the static website with the pinged results.
3. Easily display to a website visitor information about the streamer.

## Proposed Solutions

1. **Use `TwitchTools.jl` by @wookay.** This is a Julia wrapper for the Twitch API. It can ping Twitch and get streamer results back. One can run relevant queries via a GitHub integration/action.
  - **Pros:** Straightforward to use and keeps the website in pure Julia.
  - **Cons:** Requires rebuilding the static website each time to update results.

2. **Use JS and Ajax to ping Twitch.** This is a more traditional approach to pinging an API. There is plenty of support for methods like this and it would probably be easy to implement.
  - **Pros:** Simple and well-documented.
  - **Cons:** May be security vulnerabilities and adds another language into the website mix.

## Conclusion

Please share your ideas on what would be the best way to implement this feature. Thanks! :smile:

**Comment by logankilpatrick** [comment]
Rebuilding the static site is rather quick and doesn't cost us anything so that is the method I would go with to keep things simple for V0.1 but there might be a scale issue once we have millions of Julia streams ;)

**Comment by Wikunia** [comment]
Would agree after checking the Twitch API a bit. Maybe I can help out @wookay on it if I have a bit more knowledge about how the API and the authentication works.

**Comment by wookay** [comment]
yeah. `TwitchTools.jl` has transfered to Julia-Streamers org. thanks all.

**Comment by TheCedarPrince** [comment]
Hey @logankilpatrick - I agree. I am going to go ahead and close this issue since we will use proposed solution 1.

@Wikunia and @wookay, I will start a new issue discussing more about how to handle Twitch via Julia.

**Comment by TheCedarPrince** [comment]
Per @dact221, GitHub Pages has a soft limit of 10 builds per hour. Need to keep in mind for the method for building the website.
