### ISSUE TITLE
Choosing (or Making!) Best Franklin.jl Template for Streamer Website

### ISSUE THREAD

**Issue by TheCedarPrince** [Julia-Streamers/StreamerSite#3]
Please help decide on a good template for the Streamer Website!

Visit the [FranklinTemplates](https://github.com/tlienart/FranklinTemplates.jl) github page to tell us what you think should be the best template and why! :smiley:

**Comment by logankilpatrick** [comment]
Lanyon looks nice! https://github.com/poole/lanyon

**Comment by zlatanvasovic** [comment]
What will be the use of the website? You can also easily build a more suitable template with some CSS framework like Bootstrap.

**Comment by TheCedarPrince** [comment]
I like the minimalism in Lanyon @logankilpatrick! I think striving for something like that would be great in the final version. Are there any other templates similar to that or is that pretty much the best minimalist template you could find?

**Comment by findmyway** [comment]
A proposal for the landing page.

![image](https://user-images.githubusercontent.com/5612003/86317034-fe723000-bc60-11ea-9403-e7e543e30427.png)

**Comment by findmyway** [comment]
We may also need a page to list all the recordings.

Similar to this one: 

https://pythonbytes.fm/episodes/all

![image](https://user-images.githubusercontent.com/5612003/86318599-f7e5b780-bc64-11ea-83cf-72dbcd23619b.png)

**Comment by Wikunia** [comment]
That looks awesome @findmyway ! How have you designed it? Can this be exported to html/css? 
For the recorded episodes we probably need the TwitchAPI so I suppose we do that in a bit later version.

**Comment by findmyway** [comment]
Just picked a random mockup tool available online (I'm also a novice 😄 ).  The layout came into my mind when I see this issue. I guess it's not difficult to write one from scratch.

**Comment by Wikunia** [comment]
Ha okay. I know that some support to output it as a template for html/css. I'm very bad with css :laughing:

**Comment by TheCedarPrince** [comment]
@zdroid - greatly apologize for missing your comment! Not sure why I missed it. Yea, you are absolutely right. We could build something via Bootstrap. However, the goal was to somewhat keep the website in `Franklin.jl` to both support that project as well as demonstrate the abilities of Julia as somewhat of a multi-use tool.

@findmyway and @zdroid I love what you mocked up @findmyway! It looks great! @zdroid, would it be possible to make something like this as perhaps a Franklin template of sorts? Also, see issue #6 for ideas about how to solve determining who is online or not.

Thanks! :smile:

**Comment by zlatanvasovic** [comment]
@TheCedarPrince Of course, it'd be done with Franklin, just using Bootstrap for CSS (and JS, if needed). For example, https://julialang.org (Julia's official site) and https://zdroid.github.io (my site) were built with Bootstrap, with minimal changes to it.

**Comment by TheCedarPrince** [comment]
After conversation with @logankilpatrick, I have decided to use the poole/lanyon theme per his suggestion for Version 1 of the website (#7).

@zdroid, @findmyway, and @Wikunia, thank you all so much for your input! I made this decision just so we could go ahead and have something to get started. I will open up another issue for this sometime in the future for Version 2 of the website.
