### ISSUE TITLE
Logo for Streamer Website

### ISSUE THREAD

**Issue by TheCedarPrince** [Julia-Streamers/StreamerSite#4]
Help create a logo for the website! We need something that encompasses the awesome nature of the Julia Streamer community. :smiley:

(cc @abelsiqueira for his work on creating a logo already)

**Comment by logankilpatrick** [comment]
@cormullion any help on this would be appreciated!

**Comment by cormullion** [comment]
Another contribution: [this](https://github.com/cormullion/graphics/blob/master/misc/juliastreamer.svg)

**Comment by TheCedarPrince** [comment]
Ok! Like this post if you want this icon to be the logo for the Julia Streamers community! (artist: @cormullion)

## Option 1

![juliastreamer](https://user-images.githubusercontent.com/29561456/85732185-2a257100-b6c9-11ea-985a-e89ffce01b77.jpg)

**Comment by TheCedarPrince** [comment]
Ok! Like this post if you want this icon to be the logo for the Julia Streamers community! (artist: @abelsiqueria)

## Option 2

![](https://cdn.discordapp.com/attachments/711555658431987755/721511992363581500/julia-streamers-logo.png)

**Comment by TheCedarPrince** [comment]
Based on the rapid adoption of @cormullion logo already into a few facets of the Julia Streaming community, we are going to close this issue with @cormullion's logo being the winner and future icon for the Julia Streamers community! Thanks for all the other logo artwork involved in this decision-making process. :smile:

**Comment by cormullion** [comment]
Thanks! I like them both... (I kind of ignored the blue, abel remembered it :))

**Comment by TheCedarPrince** [comment]
With regards to #7
