### ISSUE TITLE
Formatting Project Directory for Website and Scripting

### ISSUE THREAD

**Issue by TheCedarPrince** [Julia-Streamers/StreamerSite#5]
@tlienart has graciously offered some direction on how we should structure the repository for this website and additional scripts that will ping API's. I will let him describe what would be best practice as we continue with this project. Thank you! :smiley:

**Comment by tlienart** [comment]
Can you give me a bit more insight in what you’re trying to achieve? Is this essentially a static site or is there something else? Do you care that the site source is in a `site` folder or not?

Best practice is to just start with a basic template without changing the folder structure (eg not putting stuff in a subfolder though you can but it requires further steps); get used to how Franklin works, then adjust the layout based on the look you want (eg if you want to use Bootstrap or whatever) then add content and deploy following the docs :)

**Comment by Wikunia** [comment]
The general idea is to use/build a TwitchAPI.jl to check which streamer is online. Which seems to be only possible with checking if anyone is online using a cronjob and rebuild the site. 
I think that will be the main feature. 
Besides that probably just a list of streamers and what they are working on. We'll probably don't need that many Franklin features for it. 

(That are just my current thought so: "Please correct me if I'm wrong" :) )

**Comment by abelsiqueira** [comment]
You can use https://shields.io/ to get the badge for twitch, so you don't
rebuild the site.

**Comment by TheCedarPrince** [comment]
CC @logankilpatrick 

Thanks for the input @tlienart and @Wikunia. Picking a basic template seems like the best option for our use cases. Should adding additional functionality to a given template be straightforward or do you suggest structuring it a different way?

**Comment by Wikunia** [comment]
Great @abelsiqueira I have shown an example in #6 now.

**Comment by TheCedarPrince** [comment]
Thank you all for the feedback! Especially @abelsiqueira and @Wikunia for testing out the shields.io badges and @tlienart for his input on how best to structure the repository. After consideration, I have decided to take your advice @tlienart and refactored the repo.

Closing the issue as this issue is solved! :smile:

**Comment by TheCedarPrince** [comment]
On our way to completing the version 1 roadmap #7 !
